version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: starburger_backend
    env_file:
      - .env
    volumes:
      - ./backend:/app
      - ./media:/app/media
      - ./bundles:/app/bundles
      - ./assets:/app/assets
      - ./staticfiles:/app/staticfiles
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: starburger_db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
    container_name: starburger_frontend
    volumes:
      - ./frontend/bundles-src:/app/bundles-src
      - ./bundles:/app/bundles
    command: ["npx", "parcel", "watch", "bundles-src/index.js", "--dist-dir", "../bundles", "--public-url", "/static/"]

  nginx:
    image: nginx:1.21
    container_name: starburger_nginx
    ports:
      - "80:80"
    volumes:
      - ./staticfiles:/var/www/static
      - ./media:/var/www/media
      - ./production/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend

volumes:
  postgres_data:
  staticfiles:
