version: '3.8'

services:
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  backend:
    build:
      context: ../backend
    command: gunicorn star_burger.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static_volume:/app/staticfiles
      - ../bundles:/app/bundles
    env_file:
      - .env
    depends_on:
      - db
    expose:
      - "8000"

  frontend:
    build:
      context: ../frontend
    volumes:
      - ../bundles:/app/bundles
    working_dir: /app
    command: >
      sh -c "npm ci &&
             npx parcel build bundles-src/index.js
             --dist-dir bundles
             --public-url='/static/'"

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - media_volume:/var/www/media
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ../bundles:/var/www/frontend
      - ../backend/staticfiles:/var/www/static:ro
    depends_on:
      - backend

volumes:
  postgres_data:
  static_volume:
  media_volume:
