# Generated by Django 3.2.15 on 2025-05-19 12:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("foodcartapp", "0038_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                default=100,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
                verbose_name="цена за единицу",
            ),
            preserve_default=False,
        ),
    ]
